---

name: Create new tag for current repository
on:

  workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          skip-github-release: true
          release-type: simple
          package-name: release-please-action